"""Initial SEO Lead Factory schema.

Hand-written rather than autogenerated so the CHECK constraints carry their
reasoning. Three of them are load-bearing and worth stating plainly:

* `ck_research_source_state` pins the ten upstream Last30Days source states. An
  eleventh value cannot be inserted, so a future normalizer bug that invents a
  state fails loudly at the database rather than quietly widening the vocabulary.

* `ck_research_evidence_observability` makes OBSERVED / ESTIMATED / UNKNOWN
  structural. There is no way to store a claim without saying how much is known
  about it.

* `uq_approval_draft` guarantees one approval history per draft. Without it, a
  rejection could be papered over by inserting a second, approving row.

Revision ID: 0001_initial
Revises:
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

JSONB = postgresql.JSONB(astext_type=sa.Text())

SOURCE_STATES = (
    "ok", "no-results", "partial", "rate-limited", "auth-failed", "unreachable",
    "timeout", "schema-drift", "skipped-unconfigured", "error",
)
OBSERVABILITY = ("OBSERVED", "ESTIMATED", "UNKNOWN")
RUN_STATUSES = ("PENDING", "RUNNING", "SUCCEEDED", "PARTIAL", "FAILED")
CONTENT_TYPES = (
    "ARTICLE", "GUIDE", "COMPARISON", "LANDING_PAGE", "LOCAL_PAGE", "FAQ_PAGE",
    "CALCULATOR", "SIMULATOR", "PROGRAMMATIC_PAGE",
)
INTENTS = ("INFORMATIONAL", "COMMERCIAL", "TRANSACTIONAL", "NAVIGATIONAL", "LOCAL")
APPROVAL_STATES = ("PENDING", "APPROVED", "REJECTED", "NEEDS_REVISION")
QA_STATUSES = ("PASSED", "FAILED", "SKIPPED")
QA_TYPES = ("DETERMINISTIC", "LLM_ASSISTED")


def _in(column: str, values: Sequence[str]) -> str:
    return f"{column} IN ({', '.join(repr(v) for v in values)})"


def upgrade() -> None:
    op.create_table(
        "vertical",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("code", sa.String(64), nullable=False, unique=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("market", sa.String(8), nullable=False),
        sa.Column("default_language", sa.String(8), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
    )

    op.create_table(
        "site",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("vertical_id", sa.Uuid(as_uuid=True),
                  sa.ForeignKey("vertical.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        # Nullable: Phase 2 has no domain and must not require one.
        sa.Column("domain", sa.String(255), nullable=True, unique=True),
        sa.Column("market", sa.String(8), nullable=False),
        sa.Column("default_language", sa.String(8), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default="PLANNED"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
    )

    op.create_table(
        "seed_keyword",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("vertical_id", sa.Uuid(as_uuid=True),
                  sa.ForeignKey("vertical.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("site_id", sa.Uuid(as_uuid=True),
                  sa.ForeignKey("site.id", ondelete="SET NULL"), nullable=True),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("normalized_query", sa.Text(), nullable=False),
        sa.Column("language", sa.String(8), nullable=False),
        sa.Column("market", sa.String(8), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default="NEW"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.UniqueConstraint("vertical_id", "normalized_query", "language", "market",
                            name="uq_seed_keyword_scope"),
    )
    op.create_index("ix_seed_keyword_vertical", "seed_keyword", ["vertical_id"])

    op.create_table(
        "research_run",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("keyword_id", sa.Uuid(as_uuid=True),
                  sa.ForeignKey("seed_keyword.id", ondelete="CASCADE"), nullable=False),
        sa.Column("provider", sa.String(64), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default="PENDING"),
        sa.Column("idempotency_key", sa.String(128), nullable=False),
        sa.Column("correlation_id", sa.String(64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("engine_commit", sa.String(64), nullable=True),
        sa.Column("engine_version", sa.String(64), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("provider_metadata", JSONB, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.UniqueConstraint("idempotency_key", name="uq_research_run_idempotency"),
        sa.CheckConstraint(_in("status", RUN_STATUSES), name="ck_research_run_status"),
    )
    op.create_index("ix_research_run_keyword", "research_run", ["keyword_id"])

    op.create_table(
        "research_source",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("research_run_id", sa.Uuid(as_uuid=True),
                  sa.ForeignKey("research_run.id", ondelete="CASCADE"), nullable=False),
        sa.Column("source_type", sa.String(64), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        # Nullable on purpose: upstream omits unknown dates rather than nulling
        # them, and inventing one here would manufacture a fact.
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("freshness_verdict", sa.String(32), nullable=True),
        sa.Column("candidate_id", sa.String(64), nullable=True),
        sa.Column("source_metadata", JSONB, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.CheckConstraint(_in("status", SOURCE_STATES),
                           name="ck_research_source_state"),
    )
    op.create_index("ix_research_source_run", "research_source", ["research_run_id"])

    op.create_table(
        "research_evidence",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("research_source_id", sa.Uuid(as_uuid=True),
                  sa.ForeignKey("research_source.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("fact", sa.Text(), nullable=False),
        sa.Column("evidence_type", sa.String(64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("observability", sa.String(16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.CheckConstraint(_in("observability", OBSERVABILITY),
                           name="ck_research_evidence_observability"),
    )
    op.create_index("ix_research_evidence_source", "research_evidence",
                    ["research_source_id"])

    op.create_table(
        "research_package",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("keyword_id", sa.Uuid(as_uuid=True),
                  sa.ForeignKey("seed_keyword.id", ondelete="CASCADE"), nullable=False),
        sa.Column("research_run_id", sa.Uuid(as_uuid=True),
                  sa.ForeignKey("research_run.id", ondelete="CASCADE"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("market", sa.String(8), nullable=False),
        sa.Column("language", sa.String(8), nullable=False),
        sa.Column("intent", sa.String(32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("facts", JSONB, nullable=False, server_default="[]"),
        sa.Column("sources", JSONB, nullable=False, server_default="[]"),
        sa.Column("user_questions", JSONB, nullable=False, server_default="[]"),
        sa.Column("unresolved_questions", JSONB, nullable=False, server_default="[]"),
        sa.Column("confidence_summary", JSONB, nullable=False, server_default="{}"),
        sa.Column("provider_provenance", JSONB, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
    )
    op.create_index("ix_research_package_keyword", "research_package", ["keyword_id"])

    op.create_table(
        "content_brief",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("research_package_id", sa.Uuid(as_uuid=True),
                  sa.ForeignKey("research_package.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("content_type", sa.String(32), nullable=False),
        sa.Column("primary_query", sa.Text(), nullable=False),
        sa.Column("search_intent", sa.String(32), nullable=False),
        sa.Column("target_audience", sa.Text(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("recommended_title", sa.Text(), nullable=False),
        sa.Column("recommended_slug", sa.String(255), nullable=False),
        sa.Column("outline", JSONB, nullable=False, server_default="[]"),
        sa.Column("key_questions", JSONB, nullable=False, server_default="[]"),
        sa.Column("required_facts", JSONB, nullable=False, server_default="[]"),
        sa.Column("required_sources", JSONB, nullable=False, server_default="[]"),
        sa.Column("cautionary_claims", JSONB, nullable=False, server_default="[]"),
        sa.Column("cta_strategy", JSONB, nullable=False, server_default="{}"),
        sa.Column("internal_linking_notes", sa.Text(), nullable=True),
        sa.Column("missing_information", JSONB, nullable=False, server_default="[]"),
        sa.Column("status", sa.String(32), nullable=False,
                  server_default="BRIEF_CREATED"),
        sa.Column("generated_by", sa.String(32), nullable=False,
                  server_default="deterministic"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.CheckConstraint(_in("content_type", CONTENT_TYPES), name="ck_brief_type"),
        sa.CheckConstraint(_in("search_intent", INTENTS), name="ck_brief_intent"),
    )
    op.create_index("ix_content_brief_package", "content_brief",
                    ["research_package_id"])

    op.create_table(
        "content_draft",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("content_brief_id", sa.Uuid(as_uuid=True),
                  sa.ForeignKey("content_brief.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("provider", sa.String(64), nullable=False),
        sa.Column("model", sa.String(128), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("meta_title", sa.Text(), nullable=True),
        sa.Column("meta_description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(32), nullable=False,
                  server_default="DRAFT_CREATED"),
        sa.Column("usage", JSONB, nullable=False, server_default="{}"),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
    )
    op.create_index("ix_content_draft_brief", "content_draft", ["content_brief_id"])

    op.create_table(
        "qa_review",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("content_draft_id", sa.Uuid(as_uuid=True),
                  sa.ForeignKey("content_draft.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("qa_type", sa.String(32), nullable=False),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("findings", JSONB, nullable=False, server_default="[]"),
        sa.Column("blocking_issues", JSONB, nullable=False, server_default="[]"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.CheckConstraint(_in("status", QA_STATUSES), name="ck_qa_status"),
        sa.CheckConstraint(_in("qa_type", QA_TYPES), name="ck_qa_type"),
    )
    op.create_index("ix_qa_review_draft", "qa_review", ["content_draft_id"])

    op.create_table(
        "approval",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("content_draft_id", sa.Uuid(as_uuid=True),
                  sa.ForeignKey("content_draft.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("state", sa.String(32), nullable=False, server_default="PENDING"),
        sa.Column("decided_by", sa.String(128), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.UniqueConstraint("content_draft_id", name="uq_approval_draft"),
        sa.CheckConstraint(_in("state", APPROVAL_STATES), name="ck_approval_state"),
    )


def downgrade() -> None:
    for table in ("approval", "qa_review", "content_draft", "content_brief",
                  "research_package", "research_evidence", "research_source",
                  "research_run", "seed_keyword", "site", "vertical"):
        op.drop_table(table)
